### ISSUE TITLE
在 Video 全屏模式下，弹幕是否支持？

### ISSUE THREAD

**Issue by SailorF** [1adybug/react-native-danmaku-player#1]
大佬，问个问题，这个组件在全屏模式下，是否支持弹幕效果

**Comment by 1adybug** [comment]
这个组件本质上就是一个完全使用 React Native 内部能力实现的 `View` 组件，没有用到任何 Android 或者 iOS 代码，所以如果你的 `Video` 组件在全屏之后，可以显示 `View` 组件在上面，那么就是可以的，参考 web 中的 `requestFullscreen` 一样，本质上就是还是在 dom 内部实现的。如果你的 `Video` 组件全屏是使用原生能力实现且无法在上面显示 `View` 组件，那就是不可以的，参考 web 中的 `requestPictureInPicture`，已经脱离了 dom 结构。

**Comment by 1adybug** [comment]
如果你的组件是第二种，完全可以自己实现全屏的逻辑，其实非常简单。

**Comment by SailorF** [comment]
感谢大佬回答！我这边了解了
